### ISSUE TITLE
Ability to add heartbeat packets and command execution

### ISSUE THREAD

**Issue by badboycxcc** [injectionmethod/Disgusting-CNC-Archives#1]
Ability to add heartbeat packets and command execution。Constant tcp connections will ddos my vps

**Comment by injectionmethod** [comment]
> Ability to add heartbeat packets and command execution。Constant tcp connections will ddos my vps

Friend if you read the name correctly you will see this is "Disgusting-CNC-Archives" not "Beautiful-CNC-Archives" 
It is also an archive, it will remain as it was...disgusting.
